name: main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  REGISTRY_NAME: codex
  CI: true
  IMAGE_NAME: proskurekov/janet

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: actions/checkout@v4

      - name: Build and push into docker hub
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.IMAGE_NAME }}
  dispatch:
    runs-on: ubuntu-latest
    needs: build-push
    permissions:
      contents: write
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.PAT }}
          repository: proskdim/base-image
          event-type: update